### ISSUE TITLE
The code seems to be missing :/

### ISSUE THREAD

**Issue by mploux** [arthur111213/VulkanFirstTest#1]
I have an issue. I can't found the code, which is a problem

**Comment by arthur111213** [comment]
Hello mploux,
Thanks for reporting this isue.
effectively, the code was missing and obviously, the project couldn't be compiled cause of that.
i fixed the isue and pushed the code so it can now be cloned and compiled with Visual Studio 2015.
Thanks again for this report.
Have a nice day,
Arthur111213

**Comment by mploux** [comment]
Thanks for the fast responding ! Have a nice one !
